//routes.http
POST http://localhost:3333/videos
Content-Type: application/json


{
  "title": "NODE",
  "description": "ESTUDE node.js",
  "duration": 180
}
 
###
// ?search="texto" (para filtrar)
GET  http://localhost:3333/videos?search=

###

PuT http://localhost:3333/videos/
Content-Type: application/json


{
  "title": "Video 03",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

DELETE  http://localhost:3333/videos/